print("Spawning cube")
graphics.new("cube", {x=0, y=1, z=0})
wait(1)
print("wait function test")
wait(1)
print("wait function test")
wait(1)
print("wait function test")
wait(1)
print("wait function test")
wait(1)
print("wait function test")
wait(1)
print("wait function test")


